[build]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "10.15.3"

[dev]
  command = "yarn run start"

[[redirects]]
  from = "/images/tiny/*"
  to = "/.netlify/images/?w=150&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/xs/*"
  to = "/.netlify/images/?w=320&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/sm/*"
  to = "/.netlify/images/?w=640&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/md/*"
  to = "/.netlify/images/?w=768&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/lg/*"
  to = "/.netlify/images/?w=1024&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/xl/*"
  to = "/.netlify/images/?w=1366&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/2xl/*"
  to = "/.netlify/images/?w=1600&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/3xl/*"
  to = "/.netlify/images/?w=1920&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/4xl/*"
  to = "/.netlify/images/?w=2148&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/5xl/*"
  to = "/.netlify/images/?w=3200&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/6xl/*"
  to = "/.netlify/images/?w=3840&fit=cover&url=/images/:splat"
  status = 200

[[redirects]]
  from = "/images/original/*"
  to = "/.netlify/images/?url=/images/:splat"
  status = 200